---
version: "3.8"
services:
  frontend:
    build:
      target: base
      cache_from:
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-base:${TAG_NAME:-latest}
        - ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-base
    image: ghcr.io/${REPOSITORY:-dev-hato/hato-atama}/frontend-base:${TAG_NAME:-latest}
