name: remove app engine environment

on:
  pull_request:

jobs:
  remove_app_engine_environment:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.2.1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - name: Get run numbers
        uses: actions/github-script@v4.1
        id: get_run_numbers
        env:
          HEAD_REF: ${{github.event.pull_request.head.ref}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const HEAD_REF = process.env["HEAD_REF"]
            const common_params = {
              owner: context.repo.owner,
              repo: context.repo.repo
            }
            console.log("call actions.listRepoWorkflows:")
            console.log(common_params)
            const workflows_res = await github.actions.listRepoWorkflows(common_params)
            const run_numbers = await Promise.all(workflows_res.data.workflows.map(async workflow => {
              if (workflow.name !== 'release') {
                return
              }

              const list_workflow_runs_params = {
                workflow_id: workflow.id,
                branch: HEAD_REF,
                ...common_params
              }
              console.log("call actions.listWorkflowRuns:")
              console.log(list_workflow_runs_params)
              const runs_res = await github.actions.listWorkflowRuns(list_workflow_runs_params)
              return runs_res.data.workflow_runs.map(run => run.run_number)
            }))
            console.log(run_numbers)
            return run_numbers.flat().filter(Boolean)
      - run: echo "${{steps.get_run_numbers.outputs.result}}"
